name: 'Blackbaud-SteveBrush - SKY UX Libraries Action'
description: 'Do not use.'
author: 'Blackbaud-SteveBrush'
branding:
  icon: 'box'
  color: 'gray-dark'
inputs:
  browser-stack-access-key:
    description: 'The BrowserStack access key.'
    required: true
  browser-stack-project:
    description: 'The BrowserStack project name. The value is arbitrary and used to identify the appropriate logs.'
    required: false
  browser-stack-username:
    description: 'The BrowserStack username.'
    required: true
  github-access-token:
    description: 'The GitHub personal access token used to commit visual test results.'
    required: true
  working-directory:
    description: 'Run the action in a different subdirectory.'
    default: './'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
