name: 'Blackbaud-SteveBrush - SKY UX Coverage'
description: 'Provide a description here'
author: 'Blackbaud-SteveBrush'
inputs:
  milliseconds:              # change this
    description: 'input description here'
    default: 0
runs:
  using: 'node12'
  main: 'dist/index.js'
