name: 'Blackbaud-SteveBrush - SKY UX Coverage'
description: 'Provide a description here'
author: 'Blackbaud-SteveBrush'
inputs:
  milliseconds:              # change this
    description: 'input description here'
    default: 0
  working-directory:
    description: 'where to run the commands'
    default: './'
runs:
  using: 'node12'
  main: 'dist/index.js'
