name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    env:
      working-directory: skyux-sdk-template
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm ci
        npm test
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Clone project
      run: git clone https://github.com/blackbaud/skyux-sdk-template -b rc-4.0.0 --single-branch
    - uses: ./
      with:
        milliseconds: 1000
      working-directory: ${{env.working-directory}}
